# 03. 넘파이
: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
: 루프 사용 X -> 빠른 배열 연산 속도
# 넘파이 ndarray 개요
: 다차원 배열

In [1]:
import numpy as np #약어

In [2]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) #1차원

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) #2차원

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) #2차원

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


array() : ndarray로 변환 (크기, 행과열, 차원)
np.array() -> ndarray로 변환을 원하는 인자 입력하면 변환함
ndarray.shape -> ndarray의 차원과 크기를 튜플 형태로 변환

In [3]:
#ndarray.ndim

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


# ndarray의 데이터 타입

In [4]:
#dtype (같은 데이터 유형)

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
#다른 데이터 유형이 섞여잇는 리스트를 ndarray로 변경 -> 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

list2 = [1, 2, 'test'] #int + string -> int형이 유니코드 문자열 값으로 변환
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0] #int + float -> int 1,2가 float64로 변환
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
#astype() -> ndarray 내 데이터값의 타입 변경
# 대용량 데이터를 만드는 경우 메모리 절약 가능

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype) #int32형을 float64로 변환

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype) #float64를 int32로 변환

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype) #float -> int 변경시 소수점 아래 삭제

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arrange, zero, ones
: 특정 크기와 차원을 가진 ndarrat흫 연속값이나 0 또는 1로 초기화해 쉽게 생성할때

In [7]:
#arange() : 파이썬 표준 함수는 range() 와 유사

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) #1차원

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
#zeros() : 모든 값을 0을 채운 해당 shape를 가진 ndarray로 변환
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones() : 모든 값을 1로 채운 해당 shape를 가진 ndarray로 변환
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()

In [9]:
#reshape : 1차원을 2차원으로 변환
#지정된 크기로 변경이 불가능하면 오류

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
#-1을 인자로 넣으면 호환 가능한 새로운 shape 으로 변환

array1 = np.arange(10) #1차원
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [11]:
#10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로는 변경 X

arrayl = np.arange(10)
array4 = arrayl.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [12]:
#reshape(-1, 1)는 무조건 2차원, 반드시 1개의 칼럼

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape) #3차원을 2차원으로 변환

array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape) #1차원을 2차원으로 변환

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)
1. 특정 데이터만 추출
2. 슬라이싱: 연속된 인덱스상의 ndarray 추출 ':' 기호 사용
3. 펜시 인덱싱: 인덱싱 집합 리스트 또는 ndarray 형태로 지정해 변환
4. 불린 인덱싱: T/F 값 인덱싱 집합을 기반으로 T에 해당하면 변환 

# 단일값 추출

In [13]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 미미
value = array1[2]
print('value:', value)
print(type(value))
#array1[2]의 타입은 더 이상 ndarray 타입이 아니고 ndarray 내의 데이터값을 미미

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [14]:
#-기호를 이용하면 맨 뒤에서부터 추출

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [15]:
#단일 인덱스를 이용해 ndarray내의 데이터값 수정

array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [16]:
#다차원 ndarray에서 단일 값 추출 (예제는 2차원)

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


# 슬라이싱
':' 사이에 시작 인덱시와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 의 위치에 있는 데이터의 ndarray를 변환
1. ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
3. ':' 기호 앞뒤로 인덱스를 생략하면 맨 처음/ 맨 마지막 인덱스로 간주

In [17]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [18]:
array1 = np.arange(1, 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
#2차원 ndarray에서 슬라이싱 (1차원과 유사)

array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[0:2, 0]\n', array2d[0:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[0:2, 0]
 [1 4]


In [21]:
#2차원에서 뒤에 오는 인덱스를 없애면 1차원으로 반환

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


# 펜시인덱싱
리스트나 ndarray로 인덱싱 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 변환

In [22]:
#2차원 ndarray에 펜시 인덱싱을 적용

array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


# 불린 인덱싱
조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용됨
단계 1.array1d>5와 같이 ndarray의 필터링 조건을 [ ]안에 기재
단계 2. False 값은 무시하고 True에 해당하는 인덱스값만 저장
단계 3. 저장된 인덱스 데이터 세트로 ndarray 조회

In [23]:
array1d = np.arange(1, 10)
# [ ] 안에 array1d>5 Boolean Indexing 적용
array3 = array1d[array1d > 5]
print('array1d >  5 인덱싱 결과 값:', array3)

array1d >  5 인덱싱 결과 값: [6 7 8 9]


In [24]:
#ndarray 객체에 조건식을 할당하면 True/False로 이뤄진 ndarray 객체 반환 / 인덱싱에 적용하면 True 값만 반환

array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [26]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


# 행렬의 정렬 - sort()와 argsort()

# 행렬 정렬
np.sort() 와 같이 넘파이에서 sort()를 호출하는 방식: 원 행렬 유지, 원 행렬의 정렬된 행렬 반환
ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식: 원 행렬 자체를 정렬한 형태로 반환, 반환값은 NONE

In [27]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 후 반환된 정렬 행렬: None
org_array.sort() 후 원본 행렬: [1 3 5 9]


In [28]:
#내림차순 정렬

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [29]:
#행렬이 2차원 이상인 경우 axis 축 값을 설정하여 행 방향 또는 열 방향으로 정렬

array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


# 정렬된 행렬의 인덱스를 반환하기
원본 행렬이 정렬되었을 때 기본 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용
정렬행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [30]:
#np.argsort()

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [31]:
#내림차순

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [32]:
#np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 펜시 인덱스로 적용해 추출

import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구기기

# 행렬 내적(행렬곱)
왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능

In [33]:
#np.dot()

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


# 전치행렬

In [34]:
#transpose()

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
